
export const products = [
  {
    id: 1,
    image: "/imgs/pb.jpg",
    title: "پاوربانک وایرلس شارژ سولار 27000 میلی آمپر پاورولوژی PP077",
    category: "پاوربانک و جامپ استارتر",
    price: 3685000,
    oldPrice: 3900000,
    status: "available",
    link: "/product/Powerology-PPBCHA77",
  },
  {
    id: 2,
    image: "/imgs/Massage.jpg",
    title: "ماساژور توپی گرین مدل Green Lion GNMABALLBK",
    category: "انواع گجت های جذاب",
    status: "sold-out",
    link: "/product/Green-GNMABALLBK",
  },
  {
    id: 3,
    image: "/imgs/juser.jpg",
    title: "جویسر 600 میلی لیتر گرین مدل Green Lion GNPJ7BLDRBK",
    category: "لوازم خانگی و شخصی",
    status: "sold-out",
    link: "/product/Green-GNPJ7BLDRB",
  },
  {
    id: 4,
    image: "/imgs/pomp.jpg",
    title: "پمپ باد گرین INFLATOR مدل Green Lion GNTYIRNFBK",
    category: "انواع گجت های جذاب",
    status: "sold-out",
    link: "/product/Green-GNTYIRNFBK",
  },
  {
    id: 5,
    image: "/imgs/idknow1.jpg",
    title: "رابط برق USB دار 65 واتی الدینیو مدل SE3338",
    category: "رابط برق و USB",
    status: "sold-out",
    link: "/product/Ldnio-SE3338",
  },
  {
    id: 6,
    image: "/imgs/idontknow2.jpg",
    title: "شارژر رومیزی 140 واتی الدینیو مدل Q4010",
    category: "شارژر رومیزی",
    price: 2295000,
    link: "/product/Ldnio-Q4010",
  },
  {
    id: 7,
    image: "/imgs/jetfan.jpg",
    title: "جت فن 150 واتی گرین مدل Green Lion GNJJPBLWR2GY",
    category: "انواع گجت های جذاب",
    status: "sold-out",
    link: "/product/Green-GNJJPBLWR2GY",
  },
  {
    id: 8,
    image: "/imgs/oraimo.jpg",
    title: "پاوربانک 27600 میلی آمپر 130 واتی اورایمو",
    category: "پاوربانک و جامپ استارتر",
    price: 5980000,
    oldPrice: 6120000,
    link: "/product/Oraimo-OPB727SQ",
  },
  {
    id: 9,
    image: "/imgs/anker.jpg",
    title: "شارژر دیواری 20 واتی انکر",
    category: "شارژر دیواری",
    price: 950000,
    link: "/product/Anker-B2348",
  },
  {
    id: 10,
    image: "/imgs/greenlion.jpg",
    title: "پاوربانک 50000 میلی آمپر 22.5 واتی گرین",
    category: "پاوربانک و جامپ استارتر",
    price: 3200000,
    link: "/product/Green-GNPWT50KPBBK",
  },
  {
    id: 11,
    image: "/imgs/mcdodo.jpg",
    title: "کابل شارژ مگنتی تایپ سی به لایتنینگ 36 واتی مک دودو",
    category: "کابل شارژ تایپ سی به لایتنینگ",
    price: 550000,
    oldPrice: 580000,
    link: "/product/Mcdodo-CA2010",
  },
];
