 "use client"

// BestSellersData.js

export const bestSellers = [
  {
    id: 1,
    title: "جامپ استاتر و پمپ باد گرین مدل Green Lion GN12VJUSTBK",
    category: "انواع گجت های جذاب",
    image: "/imgs/jump.jpg",
    oldPrice: 10400000,
    price: 8400000,
    link: "/product/Green-GN12VJUSTBK",
    colors: ["#000000"],
    status: "available",
  },
  {
    id: 2,
    title: "پمپ باد گرین INFLATOR مدل Green Lion GNTYIRNFBK",
    category: "انواع گجت های جذاب",
    image: "/imgs/pompgreenlion.jpg",
    oldPrice: null,
    price: null,
    link: "/product/Green-GNTYIRNFBK",
    colors: ["#000000"],
    status: "sold-out",
  },
  {
    id: 3,
    title: "شارژر دیواری 67 واتی گان با کابل تایپ سی مک‌دودو مدل Mcdodo CH410",
    category: "شارژر دیواری",
    image: "/imgs/mcdodoCharger.jpg",
    oldPrice: 2535000,
    price: 2299000,
    link: "/product/Mcdodo-CH410",
    colors: ["#000000", "#FFFFFF"],
    status: "available",
  },
  {
    id: 4,
    title: "شارژر دیواری 25 وات هادرون مدل Hadron C1011",
    category: "شارژر دیواری",
    image: "/imgs/hadronCharger.jpg",
    oldPrice: 750000,
    price: 720000,
    link: "/product/Hadron-C1011",
    colors: ["#000000", "#FFFFFF"],
    status: "available",
  },
  {
    id: 5,
    title: "باتری نیم قلم 10 تایی شیائومی مدل Xiaomi ZI7",
    category: "باتری آلکالاین",
    image: "/imgs/batterynim.jpg",
    oldPrice: null,
    price: 280000,
    link: "/product/Xiaomi-ZI7",
    colors: ["#0000FF"],
    status: "available",
  },
  {
    id: 6,
    title: "باتری قلمی 10تایی شیائومی مدل Xiaomi ZI5",
    category: "باتری آلکالاین",
    image: "/imgs/batteryyek.jpg",
    oldPrice: null,
    price: 299000,
    link: "/product/Xiaomi-ZI5",
    colors: ["#0000FF"],
    status: "available",
  },
  {
    id: 7,
    title: "کیبورد بلوتوثی مافی مدل Mofii Phoenix",
    category: "ماوس و کیبورد و پدموس",
    image: "/imgs/keyboardbluetooth.jpg",
    oldPrice: 2590000,
    price: 2390000,
    link: "/product/Mofii-Phoenix",
    colors: ["#000000"],
    status: "available",
  },
  {
    id: 8,
    title: "هندزفری بلوتوثی ورزشی القایی پاورولوجی مدل Powerology Pwlau008",
    category: "هندزفری بلوتوث دو گوش",
    image: "/imgs/handsfree0088.jpg",
    oldPrice: 3100000,
    price: 2800000,
    link: "/product/Powerology-Pwlau008",
    colors: ["#000000"],
    status: "available",
  },
  {
    id: 9,
    title: "شارژر دیواری گان 100 واتی الدینیو مدل Ldnio Q408",
    category: "شارژر دیواری",
    image: "/imgs/LdndCharger.jpg",
    oldPrice: 3280000,
    price: 2280000,
    link: "/product/Ldnio-Q408",
    colors: ["#000000", "#FFFFFF"],
    status: "available",
  },
  {
    id: 10,
    title: "هندزفری بلوتوثی A30i انکر مدل Anker A3958",
    category: "هندزفری بلوتوث دو گوش",
    image: "/imgs/Anker39.jpg",
    oldPrice: null,
    price: null,
    link: "/product/Anker-A3958",
    colors: ["#000000"],
    status: "sold-out",
  },
  {
    id: 11,
    title: "هاب تایپ سی 6 کاره انکر مدل Anker A8363",
    category: "انواع گجت های جذاب",
    image: "/imgs/Anker83.jpg",
    oldPrice: null,
    price: null,
    link: "/product/Anker-A8363",
    colors: ["#C0C0C0", "#000000"],
    status: "sold-out",
  },
];
